Add transfers for using arguments
openrewrite/rewrite-jackson pull request #16
Opened 2024-10-23 12:43 UTC by nielsdebruin

## What's changed?
The `RemoveDoublyAnnotatedCodehausAnnotations` recipe has been extended with the functionality to transfer the value of "using" in the codehaus annotations`@JsonSerialize(using=XYZ)` to the faster XML annotation.The transfer only occurs if no value for `using` has been specified in the fasterxml annotation. An option has been added to enable or disable this behavior

## Anything in particular you'd like reviewers to focus on?

## Anyone you would like to review specifically?
@Laurens-W @timtebeek 

### Checklist
- [x] I've added unit tests to cover both positive and negative cases
- [x] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [x] I've used the IntelliJ IDEA auto-formatter on affected files

2024-10-23 13:01 UTC, timtebeek commented
I'd prefer to keep `RemoveDoublyAnnotatedCodehausAnnotations` as a recipe that merely removes annotations, and does not itself do any conversion.

Can we move this visitor into a either the existing `JsonIncludeAnnotation` recipe, or a standalone recipe?

2024-10-23 15:22 UTC, timtebeek commented on src/main/java/org/openrewrite/java/jackson/codehaus/TransferUsingArgumentFromCodehausToFasterXML.java
> +public class TransferUsingArgumentFromCodehausToFasterXML extends Recipe {
Be sure to also link it into the relevant yaml recipe in src/main/resources

2024-10-24 09:36 UTC, timtebeek reviewed
Thanks for the work & rework here @nielsdebruin ; ended up removing the troublesome auto format; when in doubt that's typically easiest.

2024-10-24 09:51 UTC, timtebeek approved these changes
Added a few more polishes, like also converting known serializer packages to fasterxml databind. Thanks for getting this most of the way there!

2024-10-24 09:51 UTC, timtebeek commented on src/test/java/org/openrewrite/java/jackson/codehaus/TransferUsingArgumentFromCodehausToFasterXMLTest.java
> +                @com.fasterxml.jackson.databind.annotation.JsonSerialize(using = None.class)
What I found slightly odd about the "after" usage example here is that we're one-to-one moving the argument over, whereas the `using` argument here, as well as the `contentUsing`, `keyUsing` and `nullsUsing` sibling only accept a FasterXml JsonSerializer, whereas the moved argument is a Codehaus JsonSerialzer, That means after this recipe the code would not yet compile. Compare the before and after packages:

![image](https://github.com/user-attachments/assets/3127a4ce-0b17-46e0-b65c-b69ec9613e67) ![image](https://github.com/user-attachments/assets/fc44fbcf-016a-4f6b-8dae-7f03963d57d7)

That means we likely need to expand the converted packages (ideally) and types (for exceptional cases) seen here:
https://github.com/openrewrite/rewrite-jackson/blob/b5fab130a8a7a90774582b1eda0ec0b58217bab6/src/main/resources/META-INF/rewrite/codehaus-to-fasterxml.yml#L32-L62

2024-10-24 09:51 UTC, timtebeek commented on src/test/java/org/openrewrite/java/jackson/codehaus/TransferUsingArgumentFromCodehausToFasterXMLTest.java
> +                @com.fasterxml.jackson.databind.annotation.JsonSerialize(using = None.class)
Pushed up in https://github.com/openrewrite/rewrite-jackson/pull/16/commits/736fce00e97139dd7a30f5aa529d6bb0c3e575d2.

2024-10-24 10:06 UTC, timtebeek requested changes
Before we merge; would you mind handling the other using arguments the same?
> contentUsing, keyUsing and nullsUsing

2024-10-24 11:38 UTC, nielsdebruin commented
> Before we merge; would you mind handling the other using arguments the same?
> 
> > contentUsing, keyUsing and nullsUsing

On it

2024-10-24 16:23 UTC, nielsdebruin commented on src/main/java/org/openrewrite/java/jackson/codehaus/TransferJsonSerializeArgumentsFromCodehausToFasterXML.java
> +                        transferArgument(doubleAnnotated, "using");
Done

2024-10-24 16:56 UTC, Laurens-W approved these changes

2024-10-27 19:40 UTC, timtebeek approved these changes

2024-10-27 19:40 UTC, merged